# Site Info
title:              "June Kim"
description:        "Thoughts on software, life, and everything"
google_verify:       # Put your Google Verification here
google_analytics:    # Put your Google Analytics code

# Author Info
author_name:        "June Kim"
author_email:       june@june.kim
author_gravatar:    a162fa4928ebc00907f6cc47727cbb6c # Gravatar md5 hash

social:
  facebook: kimjune
  github: kimjune01
  linkedin: kimjune01
  instagram: kimjune01

plugins:
  - jekyll-feed

# Github Pages
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll
lsi: false
safe: true
source: .
incremental: false
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
weburl:             https://www.june.kim
asseturl:           https://raw.githubusercontent.com/kimjune01/kimjune01.github.io/master/assets
permalink:          /:title # Post permalink
timezone:           Canada/Pacific # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:       rouge 
sass:
  style: compressed
  quiet_deps: true
  silence_deprecations:
    - import

#
tag_page_layout: tag_page
tag_page_dir: tag

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile"]

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
